postgres:
  image: postgres:alpine
  restart: always
  container_name: illeryDB
  ports:
    - '5000:5432'
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: illeryDB
  volumes:
    - ./init:/docker-entrypoint-initdb.d/